# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/stage/plugins/pageeffects/iriswipe/kpr_pageeffect_iriswipe_autogen/mocs_compilation.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/Plugin.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/KPrIrisWipeEffectStrategyBase.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/irisWipe/KPrIrisWipeEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/triangleWipe/KPrTriangleWipeEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/arrowHeadWipe/KPrArrowHeadWipeEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/ellipseWipe/KPrEllipseWipeEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/roundRectWipe/KPrRoundRectWipeEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/pentagonWipe/KPrPentagonWipeEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/hexagonWipe/KPrHexagonWipeEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/starWipe/KPrStarWipeEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/eyeWipe/KPrEyeWipeEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/iriswipe/miscShapeWipe/KPrMiscShapeWipeEffectFactory.cpp
