# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/stage/plugins/pageeffects/swapeffect/kpr_pageeffect_swapeffect_autogen/mocs_compilation.cpp \
    ../../../../../../stage/plugins/pageeffects/swapeffect/Plugin.cpp \
    ../../../../../../stage/plugins/pageeffects/swapeffect/KPrSwapEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/swapeffect/KPrSwapEffectHorizontalStrategy.cpp
