# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../calligra/filters/karbon/image/ui_ImageExportOptionsWidget.h
SOURCES += ../../../../calligra/filters/karbon/image/calligra_filter_karbon2image_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/filters/karbon/image/ImageExport.cpp \
    ../../../../../src/calligra-v3.2.1/filters/karbon/image/ImageExportOptionsWidget.cpp
FORMS += ../../../../../src/calligra-v3.2.1/filters/karbon/image/ImageExportOptionsWidget.ui
