# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/filters/words/mobi/calligra_filter_odt2mobi_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/mobi/MobiExportDebug.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/mobi/exportmobi.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/mobi/MobiHeaderGenerator.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/mobi/MobiFile.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/mobi/PalmDocCompression.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/mobi/OdtMobiHtmlConverter.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/epub/FileCollector.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/epub/OdfParser.cpp
