# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/stage/part/tools/animationtool/calligrastagetoolanimation_autogen/mocs_compilation.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/Plugin.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrAnimationTool.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrAnimationToolFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrPageEffectDocker.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrClickActionDocker.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrShapeAnimationDocker.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrEditAnimationsWidget.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrCollectionItemModel.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrAnimationGroupProxyModel.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrAnimationSelectorWidget.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrPredefinedAnimationsLoader.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrAnimationsTimeLineView.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrTimeLineHeader.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/part/tools/animationtool/KPrTimeLineView.cpp
