# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../calligra/plugins/defaultTools/ui_DefaultToolWidget.h \
    ../../../calligra/plugins/defaultTools/ui_DefaultToolArrangeWidget.h \
    ../../../calligra/plugins/defaultTools/ui_DefaultToolTransformWidget.h \
    ../../../calligra/plugins/defaultTools/ui_GuidesToolOptionWidget.h \
    ../../../calligra/plugins/defaultTools/ui_InsertGuidesToolOptionWidget.h \
    ../../../calligra/plugins/defaultTools/ui_ConnectionPointWidget.h
SOURCES += ../../../calligra/plugins/defaultTools/calligra_tool_defaults_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/Plugin.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/DefaultTool.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/DefaultToolFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/DefaultToolWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/DefaultToolArrangeWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/DefaultToolTransformWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/ShapeMoveStrategy.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/ShapeResizeStrategy.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/ShapeRotateStrategy.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/ShapeShearStrategy.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/SelectionDecorator.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/SelectionTransformCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/ChartResizeStrategy.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/guidestool/GuidesTool.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/guidestool/GuidesToolFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/guidestool/GuidesToolOptionWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/guidestool/InsertGuidesToolOptionWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/connectionTool/ConnectionTool.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/connectionTool/ConnectionToolFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/connectionTool/AddConnectionPointCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/connectionTool/RemoveConnectionPointCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/connectionTool/ChangeConnectionPointCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/connectionTool/MoveConnectionPointStrategy.cpp \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/connectionTool/ConnectionPointWidget.cpp
FORMS += ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/DefaultToolWidget.ui \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/DefaultToolArrangeWidget.ui \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/defaulttool/DefaultToolTransformWidget.ui \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/guidestool/GuidesToolOptionWidget.ui \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/guidestool/InsertGuidesToolOptionWidget.ui \
    ../../../../src/calligra-v3.2.1/plugins/defaultTools/connectionTool/ConnectionPointWidget.ui
