# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/stage/plugins/pageeffects/matrixwipe/kpr_pageeffect_matrixwipe_autogen/mocs_compilation.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/Plugin.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/KPrMatrixWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/snakewipe/KPrSnakeWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/snakewipe/KPrSnakeWipeBottomRightHorizontalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/snakewipe/KPrSnakeWipeBottomRightVerticalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/snakewipe/KPrSnakeWipeTopLeftHorizontalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/snakewipe/KPrSnakeWipeTopLeftVerticalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/snakewipe/KPrSnakeWipeDiagonalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/snakewipe/KPrSnakeWipeTopLeftDiagonalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/snakewipe/KPrSnakeWipeTopRightDiagonalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/snakewipe/KPrSnakeWipeBottomRightDiagonalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/snakewipe/KPrSnakeWipeBottomLeftDiagonalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/spiralwipe/KPrSpiralWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/spiralwipe/KPrSpiralWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/parallelsnakes/KPrParallelSnakesWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/parallelsnakes/KPrParallelSnakesWipeHorizontalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/parallelsnakes/KPrParallelSnakesWipeVerticalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/parallelsnakes/KPrParallelSnakesWipeDiagonalStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/boxsnakes/KPrBoxSnakesWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/boxsnakes/KPrBoxSnakesWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/waterfallwipe/KPrWaterfallWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/waterfallwipe/KPrWaterfallWipeTopLeftStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/waterfallwipe/KPrWaterfallWipeTopRightStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/waterfallwipe/KPrWaterfallWipeBottomLeftStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/matrixwipe/waterfallwipe/KPrWaterfallWipeBottomRightStrategy.cpp
