# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../calligra/plugins/pictureshape/ui_wdgPictureTool.h
SOURCES += ../../../calligra/plugins/pictureshape/calligra_shape_picture_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/PictureDebug.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/PictureShape.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/PictureShapeFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/PictureTool.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/PictureToolFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/Plugin.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/PictureShapeConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/ChangeImageCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/ClipCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/CropWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/SelectionRect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/ClippingRect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/filters/GreyscaleFilterEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/filters/MonoFilterEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/filters/WatermarkFilterEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/filters/ColoringFilterEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/pictureshape/filters/GammaFilterEffect.cpp
FORMS += ../../../../src/calligra-v3.2.1/plugins/pictureshape/forms/wdgPictureTool.ui
