# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/stage/plugins/pageeffects/barwipe/kpr_pageeffect_barwipe_autogen/mocs_compilation.cpp \
    ../../../../../../stage/plugins/pageeffects/barwipe/Plugin.cpp \
    ../../../../../../stage/plugins/pageeffects/barwipe/KPrBarWipeEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/barwipe/KPrBarWipeFromLeftStrategy.cpp \
    ../../../../../../stage/plugins/pageeffects/barwipe/KPrBarWipeFromRightStrategy.cpp \
    ../../../../../../stage/plugins/pageeffects/barwipe/KPrBarWipeFromTopStrategy.cpp \
    ../../../../../../stage/plugins/pageeffects/barwipe/KPrBarWipeFromBottomStrategy.cpp
