# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../calligra/words/part/ui_KWFrameConnectSelector.h \
    ../../../calligra/words/part/ui_KWRunAroundProperties.h \
    ../../../calligra/words/part/ui_KWAnchoringProperties.h \
    ../../../calligra/words/part/ui_KWDocumentColumns.h \
    ../../../calligra/words/part/ui_KWStartupWidget.h \
    ../../../calligra/words/part/ui_KWCreateBookmark.h \
    ../../../calligra/words/part/ui_KWSelectBookmark.h \
    ../../../calligra/words/part/ui_KWInsertImage.h \
    ../../../calligra/words/part/ui_StatisticsPreferencesPopup.h \
    ../../../calligra/words/part/ui_SimpleSetupWidget.h \
    ../../../calligra/words/part/ui_SimpleHeaderFooterWidget.h
SOURCES += ../../../calligra/words/part/wordsprivate_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWFactory.cpp \
    ../../../../src/calligra-v3.2.1/words/part/WordsDebug.cpp \
    ../../../../src/calligra-v3.2.1/words/part/Words.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWApplicationConfig.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWCanvasBase.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWCanvas.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWCanvasItem.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWDocument.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWGui.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWView.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWPart.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWPage.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWPageCacheManager.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWPageManager.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWPageStyle.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWViewMode.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWViewModeNormal.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWViewModePreview.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWStatusBar.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWOdfLoader.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWOdfWriter.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWOdfSharedLoadingData.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWRootAreaProviderBase.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWRootAreaProviderTextBox.cpp \
    ../../../../src/calligra-v3.2.1/words/part/KWRootAreaProvider.cpp \
    ../../../../src/calligra-v3.2.1/words/part/pagetool/KWPageTool.cpp \
    ../../../../src/calligra-v3.2.1/words/part/pagetool/KWPageToolFactory.cpp \
    ../../../../src/calligra-v3.2.1/words/part/pagetool/SimpleSetupWidget.cpp \
    ../../../../src/calligra-v3.2.1/words/part/pagetool/SimpleHeaderFooterWidget.cpp \
    ../../../../src/calligra-v3.2.1/words/part/frames/KWFrameLayout.cpp \
    ../../../../src/calligra-v3.2.1/words/part/frames/KWFrame.cpp \
    ../../../../src/calligra-v3.2.1/words/part/frames/KWFrameSet.cpp \
    ../../../../src/calligra-v3.2.1/words/part/frames/KWTextFrameSet.cpp \
    ../../../../src/calligra-v3.2.1/words/part/frames/KWCopyShape.cpp \
    ../../../../src/calligra-v3.2.1/words/part/widgets/KoFindToolbar.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWFrameConnectSelector.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWRunAroundProperties.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWAnchoringProperties.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWFrameDialog.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWShapeConfigFactory.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWDocumentColumns.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWStartupWidget.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWPageSettingsDialog.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWPrintingDialog.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWCreateBookmarkDialog.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWSelectBookmarkDialog.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWConfigureDialog.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dockers/KWStatisticsDocker.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dockers/KWStatisticsWidget.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dockers/StatisticsPreferencesPopup.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dockers/KWNavigationDocker.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dockers/KWNavigationDockerFactory.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dockers/KWNavigationWidget.cpp \
    ../../../../src/calligra-v3.2.1/words/part/commands/KWPageStylePropertiesCommand.cpp \
    ../../../../src/calligra-v3.2.1/words/part/commands/KWNewPageStyleCommand.cpp \
    ../../../../src/calligra-v3.2.1/words/part/commands/KWChangePageStyleCommand.cpp \
    ../../../../src/calligra-v3.2.1/words/part/commands/KWShapeCreateCommand.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dockers/KWDebugDocker.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dockers/KWDebugDockerFactory.cpp \
    ../../../../src/calligra-v3.2.1/words/part/dockers/KWDebugWidget.cpp
FORMS += ../../../../src/calligra-v3.2.1/words/part/dialogs/KWFrameConnectSelector.ui \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWRunAroundProperties.ui \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWAnchoringProperties.ui \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWDocumentColumns.ui \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWStartupWidget.ui \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWCreateBookmark.ui \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWSelectBookmark.ui \
    ../../../../src/calligra-v3.2.1/words/part/dialogs/KWInsertImage.ui \
    ../../../../src/calligra-v3.2.1/words/part/dockers/StatisticsPreferencesPopup.ui \
    ../../../../src/calligra-v3.2.1/words/part/pagetool/SimpleSetupWidget.ui \
    ../../../../src/calligra-v3.2.1/words/part/pagetool/SimpleHeaderFooterWidget.ui
