# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../calligra/plugins/textediting/autocorrection/ui_AutocorrectConfig.h
SOURCES += ../../../../calligra/plugins/textediting/autocorrection/calligra_textediting_autocorrect_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/autocorrection/AutocorrectDebug.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/autocorrection/AutocorrectPlugin.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/autocorrection/Autocorrect.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/autocorrection/AutocorrectFactory.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/autocorrection/AutocorrectConfigDialog.cpp
FORMS += ../../../../../src/calligra-v3.2.1/plugins/textediting/autocorrection/AutocorrectConfig.ui
