# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../calligra/plugins/stencilsdocker/calligra_docker_stencils_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/plugins/stencilsdocker/StencilBoxDebug.cpp \
    ../../../../src/calligra-v3.2.1/plugins/stencilsdocker/StencilBoxPlugin.cpp \
    ../../../../src/calligra-v3.2.1/plugins/stencilsdocker/StencilBoxDocker.cpp \
    ../../../../src/calligra-v3.2.1/plugins/stencilsdocker/StencilListView.cpp \
    ../../../../src/calligra-v3.2.1/plugins/stencilsdocker/CollectionTreeWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/stencilsdocker/CollectionItemModel.cpp \
    ../../../../src/calligra-v3.2.1/plugins/stencilsdocker/StencilShapeFactory.cpp
