# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ./calligra_filter_wpd2odt_autogen/mocs_compilation.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/wordperfect/import/WPDImport.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/outputhelper/StringDocumentHandler.cxx \
    ../../../../../../src/calligra-v3.2.1/filters/outputhelper/FemtoZip.cxx \
    ../../../../../../src/calligra-v3.2.1/filters/outputhelper/OutputFileHelper.cxx
