# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/stage/plugins/pageeffects/fade/kpr_pageeffect_fade_autogen/mocs_compilation.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/fade/Plugin.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/fade/KPrFadeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/fade/KPrFadeCrossStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/fade/KPrFadeOverColorStrategy.cpp
