# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/stage/plugins/pageeffects/spacerotation/kpr_pageeffect_spacerotation_autogen/mocs_compilation.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/spacerotation/Plugin.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/spacerotation/KPrSpaceRotationEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/spacerotation/KPrSpaceRotationFromBottomStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/spacerotation/KPrSpaceRotationFromTopStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/spacerotation/KPrSpaceRotationFromRightStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/spacerotation/KPrSpaceRotationFromLeftStrategy.cpp
