# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../calligra/filters/libmsooxml/komsooxml_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlDebug.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlGlobal.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlUtils.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlCommonReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlThemesReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlRelationshipsReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlRelationships.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlImport.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlDocPropertiesReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlDiagramReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlDiagramReader_p.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/ooxml_pole.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlDrawingTableStyleReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlDrawingTableStyle.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/MsooXmlTableStyle.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/VmlDrawingReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/PredefinedShapeHelper.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/ComplexShapeHandler.cpp \
    ../../../../src/calligra-v3.2.1/filters/sheets/xlsx/XlsxChartOdfWriter.cpp \
    ../../../../src/calligra-v3.2.1/filters/libmsooxml/KoOdfExporter.cpp
