# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/plugins/textediting/changecase/calligra_textediting_changecase_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/changecase/ChangecaseDebug.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/changecase/ChangecasePlugin.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/changecase/Changecase.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/changecase/ChangecaseFactory.cpp
