# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/filters/words/wiki/export/calligra_filter_odt2wiki_autogen/mocs_compilation.cpp \
    ../../../../../../filters/words/wiki/export/WikiExportDebug.cpp \
    ../../../../../../filters/words/wiki/export/WikiExport.cpp \
    ../../../../../../filters/words/wiki/export/OdtReaderWikiBackend.cpp \
    ../../../../../../filters/words/wiki/export/OdfReaderWikiContext.cpp
