# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/plugins/textediting/spellcheck/calligra_textediting_spellcheck_autogen/mocs_compilation.cpp \
    ../../../../../plugins/textediting/spellcheck/SpellCheckDebug.cpp \
    ../../../../../plugins/textediting/spellcheck/SpellCheckPlugin.cpp \
    ../../../../../plugins/textediting/spellcheck/SpellCheck.cpp \
    ../../../../../plugins/textediting/spellcheck/SpellCheckFactory.cpp \
    ../../../../../plugins/textediting/spellcheck/BgSpellCheck.cpp \
    ../../../../../plugins/textediting/spellcheck/SpellCheckMenu.cpp
