# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/stage/plugins/pageeffects/clockwipe/kpr_pageeffect_clockwipe_autogen/mocs_compilation.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/Plugin.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/KPrClockWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/KPrCenterFanWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/KPrSideFanWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/KPrClockWipeSubpathHelper.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/KPrSweepWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/clockwipe/KPrClockWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/pinwheelwipe/KPrPinWheelWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/singlesweepwipe/KPrSingleSweepWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/singlesweepwipe/KPrSingleSweepWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/fanwipe/KPrFanWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/doublefanwipe/KPrDoubleFanWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/doublesweepwipe/KPrDoubleSweepWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/doublesweepwipe/KPrDoubleSweepWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/saloondoorwipe/KPrSaloonDoorWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/saloondoorwipe/KPrSaloonDoorWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/windshieldwipe/KPrWindShieldWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/clockwipe/windshieldwipe/KPrWindShieldWipeStrategy.cpp
