# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../calligra/plugins/pathshapes/ui_StarShapeConfigWidget.h \
    ../../../calligra/plugins/pathshapes/ui_RectangleShapeConfigWidget.h \
    ../../../calligra/plugins/pathshapes/ui_EllipseShapeConfigWidget.h \
    ../../../calligra/plugins/pathshapes/ui_SpiralShapeConfigWidget.h
SOURCES += ../../../calligra/plugins/pathshapes/calligra_shape_paths_autogen/mocs_compilation.cpp \
    ../../../../plugins/pathshapes/ellipse/EllipseShape.cpp \
    ../../../../plugins/pathshapes/ellipse/EllipseShapeFactory.cpp \
    ../../../../plugins/pathshapes/ellipse/EllipseShapeConfigWidget.cpp \
    ../../../../plugins/pathshapes/ellipse/EllipseShapeConfigCommand.cpp \
    ../../../../plugins/pathshapes/spiral/SpiralShape.cpp \
    ../../../../plugins/pathshapes/spiral/SpiralShapeFactory.cpp \
    ../../../../plugins/pathshapes/spiral/SpiralShapeConfigWidget.cpp \
    ../../../../plugins/pathshapes/spiral/SpiralShapeConfigCommand.cpp \
    ../../../../plugins/pathshapes/star/StarShape.cpp \
    ../../../../plugins/pathshapes/star/StarShapeFactory.cpp \
    ../../../../plugins/pathshapes/star/StarShapeConfigWidget.cpp \
    ../../../../plugins/pathshapes/star/StarShapeConfigCommand.cpp \
    ../../../../plugins/pathshapes/rectangle/RectangleShape.cpp \
    ../../../../plugins/pathshapes/rectangle/RectangleShapeFactory.cpp \
    ../../../../plugins/pathshapes/rectangle/RectangleShapeConfigWidget.cpp \
    ../../../../plugins/pathshapes/rectangle/RectangleShapeConfigCommand.cpp \
    ../../../../plugins/pathshapes/enhancedpath/EnhancedPathShape.cpp \
    ../../../../plugins/pathshapes/enhancedpath/EnhancedPathShapeFactory.cpp \
    ../../../../plugins/pathshapes/enhancedpath/EnhancedPathCommand.cpp \
    ../../../../plugins/pathshapes/enhancedpath/EnhancedPathParameter.cpp \
    ../../../../plugins/pathshapes/enhancedpath/EnhancedPathFormula.cpp \
    ../../../../plugins/pathshapes/enhancedpath/EnhancedPathHandle.cpp \
    ../../../../plugins/pathshapes/enhancedpath/CalloutShape.cpp \
    ../../../../plugins/pathshapes/enhancedpath/CalloutShapeFactory.cpp \
    ../../../../plugins/pathshapes/enhancedpath/CalloutContainerModel.cpp \
    ../../../../plugins/pathshapes/enhancedpath/CalloutToolFactory.cpp \
    ../../../../plugins/pathshapes/enhancedpath/CalloutDebug.cpp \
    ../../../../plugins/pathshapes/PathShapesPlugin.cpp
FORMS += ../../../../plugins/pathshapes/star/StarShapeConfigWidget.ui \
    ../../../../plugins/pathshapes/rectangle/RectangleShapeConfigWidget.ui \
    ../../../../plugins/pathshapes/ellipse/EllipseShapeConfigWidget.ui \
    ../../../../plugins/pathshapes/spiral/SpiralShapeConfigWidget.ui
