# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/filters/stage/powerpoint/ppttoodplib_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/filters/stage/powerpoint/PptDebug.cpp \
    ../../../../../src/calligra-v3.2.1/filters/stage/powerpoint/PptToOdp.cpp \
    ../../../../../src/calligra-v3.2.1/filters/stage/powerpoint/ParsedPresentation.cpp \
    ../../../../../src/calligra-v3.2.1/filters/stage/powerpoint/DateTimeFormat.cpp \
    ../../../../../src/calligra-v3.2.1/filters/stage/powerpoint/pptstyle.cpp
