# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/filters/stage/pptx/calligra_filter_pptx2odp_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/filters/stage/pptx/PptxDebug.cpp \
    ../../../../../src/calligra-v3.2.1/filters/stage/pptx/PptxImport.cpp \
    ../../../../../src/calligra-v3.2.1/filters/stage/pptx/PptxXmlDocumentReader.cpp \
    ../../../../../src/calligra-v3.2.1/filters/stage/pptx/PptxXmlSlideReader.cpp \
    ../../../../../src/calligra-v3.2.1/filters/stage/pptx/PptxXmlCommentsReader.cpp \
    ../../../../../src/calligra-v3.2.1/filters/stage/pptx/PptxXmlCommentAuthorsReader.cpp \
    ../../../../../src/calligra-v3.2.1/filters/sheets/xlsx/XlsxChartOdfWriter.cpp \
    ../../../../../src/calligra-v3.2.1/filters/sheets/xlsx/XlsxXmlChartReader.cpp
