# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/filters/karbon/eps/calligra_filter_eps2svgai_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/filters/karbon/eps/EpsImport.cpp \
    ../../../../../src/calligra-v3.2.1/filters/karbon/eps/PsCommentLexer.cpp
