# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../calligra/filters/words/ascii/ui_ImportDialogUI.h
SOURCES += ../../../../calligra/filters/words/ascii/calligra_filter_ascii2words_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/ascii/AsciiImportDebug.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/ascii/AsciiImport.cpp
FORMS += ../../../../../src/calligra-v3.2.1/filters/words/ascii/ImportDialogUI.ui
