# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/filters/words/ascii/calligra_filter_odt2ascii_autogen/mocs_compilation.cpp \
    ../../../../../filters/words/ascii/AsciiExportDebug.cpp \
    ../../../../../filters/words/ascii/AsciiExport.cpp \
    ../../../../../filters/words/ascii/OdtReaderAsciiBackend.cpp \
    ../../../../../filters/words/ascii/OdfReaderAsciiContext.cpp
