# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/filters/words/docx/export/calligra_filter_odt2docx_autogen/mocs_compilation.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/DocxExportDebug.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/DocxExport.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/DocxStyleWriter.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/DocxStyleHelper.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/OdfReaderDocxContext.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/OdtReaderDocxBackend.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/OdfTextReaderDocxBackend.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/FileCollector.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/DocxFile.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/UnitConversions.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/OpcContentTypes.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/OpcRelSet.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/export/OpcRelSetManager.cpp
