# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/stage/plugins/pageeffects/slidewipe/kpr_pageeffect_slidewipe_autogen/mocs_compilation.cpp \
    ../../../../../../stage/plugins/pageeffects/slidewipe/Plugin.cpp \
    ../../../../../../stage/plugins/pageeffects/slidewipe/KPrSlideWipeEffectFactory.cpp \
    ../../../../../../stage/plugins/pageeffects/slidewipe/KPrSlideWipeFromBottomStrategy.cpp \
    ../../../../../../stage/plugins/pageeffects/slidewipe/KPrSlideWipeFromLeftStrategy.cpp \
    ../../../../../../stage/plugins/pageeffects/slidewipe/KPrSlideWipeFromRightStrategy.cpp \
    ../../../../../../stage/plugins/pageeffects/slidewipe/KPrSlideWipeFromTopStrategy.cpp \
    ../../../../../../stage/plugins/pageeffects/slidewipe/KPrSlideWipeToBottomStrategy.cpp \
    ../../../../../../stage/plugins/pageeffects/slidewipe/KPrSlideWipeToLeftStrategy.cpp \
    ../../../../../../stage/plugins/pageeffects/slidewipe/KPrSlideWipeToRightStrategy.cpp \
    ../../../../../../stage/plugins/pageeffects/slidewipe/KPrSlideWipeToTopStrategy.cpp
