# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/plugins/textediting/thesaurus/calligra_textediting_thesaurus_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/thesaurus/ThesaurusDebug.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/thesaurus/Thesaurus.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/thesaurus/ThesaurusPlugin.cpp \
    ../../../../../src/calligra-v3.2.1/plugins/textediting/thesaurus/ThesaurusFactory.cpp
