# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/filters/words/epub/calligra_filter_odt2html_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/epub/HtmlExportDebug.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/epub/exporthtml.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/epub/OdfParser.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/epub/OdtHtmlConverter.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/epub/HtmlFile.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/epub/FileCollector.cpp
