# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../calligra/libs/pageapp/ui_BackgroundToolWidget.h
SOURCES += ../../../calligra/libs/pageapp/kopageapp_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/PageAppDebug.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPADocument.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoShapeTraversal.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAView.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAViewBase.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPACanvas.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPACanvasItem.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPACanvasBase.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPASavingContext.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAPixmapCache.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAPageBase.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAMasterPage.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAPage.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAPageContainerModel.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAViewMode.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAViewModeNormal.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPALoadingContext.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAOdfPageSaveHelper.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAPastePage.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPADocumentModel.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAPageThumbnailModel.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPADocumentStructureDocker.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAUtil.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAPrintJob.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPATextPage.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/KoPAPageProvider.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/commands/KoPAPageInsertCommand.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/commands/KoPAPageDeleteCommand.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/commands/KoPAPageMoveCommand.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/commands/KoPAChangeMasterPageCommand.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/commands/KoPAChangePageLayoutCommand.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/commands/KoPADisplayMasterShapesCommand.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/commands/KoPADisplayMasterBackgroundCommand.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/dialogs/KoPAMasterPageDialog.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/dialogs/KoPAPageLayoutDialog.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/dialogs/KoPAConfigureDialog.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/widgets/KoPageNavigator.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/widgets/KoPageNavigatorButton.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/widgets/KoPABackgroundFillWidget.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/tools/backgroundTool/KoPABackgroundTool.cpp \
    ../../../../src/calligra-v3.2.1/libs/pageapp/tools/backgroundTool/KoPABackgroundToolWidget.cpp
FORMS += ../../../../src/calligra-v3.2.1/libs/pageapp/tools/backgroundTool/BackgroundToolWidget.ui
