# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/stage/plugins/eventactions/calligrastageeventactions_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/stage/plugins/eventactions/sound/KPrSoundEventAction.cpp \
    ../../../../../src/calligra-v3.2.1/stage/plugins/eventactions/sound/KPrSoundEventActionFactory.cpp \
    ../../../../../src/calligra-v3.2.1/stage/plugins/eventactions/sound/KPrSoundEventActionWidget.cpp \
    ../../../../../src/calligra-v3.2.1/stage/plugins/eventactions/Plugin.cpp
