# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/filters/words/docx/import/calligra_filter_docx2odt_autogen/mocs_compilation.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxDebug.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxXmlStylesReader.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxXmlFontTableReader.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxXmlCommentsReader.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxXmlDocumentReader.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxXmlHeaderReader.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxXmlFooterReader.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxXmlNumberingReader.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxXmlFootnoteReader.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxXmlEndnoteReader.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxXmlSettingsReader.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/words/docx/import/DocxImport.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/sheets/xlsx/XlsxChartOdfWriter.cpp \
    ../../../../../../src/calligra-v3.2.1/filters/sheets/xlsx/XlsxXmlChartReader.cpp
