# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/stage/plugins/pageeffects/edgewipe/kpr_pageeffect_edgewipe_autogen/mocs_compilation.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/Plugin.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/miscdiagonalwipe/MiscDiagonalWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/miscdiagonalwipe/DoubleBarnDoorWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/miscdiagonalwipe/DoubleDiamondWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/fourboxwipe/FourBoxWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/fourboxwipe/CornersInWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/fourboxwipe/CornersOutWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/diagonalwipe/DiagonalWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/diagonalwipe/DiagonalWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/barndoorwipe/BarnDoorWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/barndoorwipe/BarnDoorWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/boxwipe/BoxWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/boxwipe/BoxWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/veewipe/VeeWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/veewipe/VeeWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/barnveewipe/BarnVeeWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/barnveewipe/BarnVeeWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/zigzagwipe/ZigZagWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/zigzagwipe/ZigZagWipeStrategy.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/barnzigzagwipe/BarnZigZagWipeEffectFactory.cpp \
    ../../../../../../src/calligra-v3.2.1/stage/plugins/pageeffects/edgewipe/barnzigzagwipe/BarnZigZagWipeStrategy.cpp
