# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../calligra/libs/widgetutils/kowidgetutils_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/libs/widgetutils/KoGroupButton.cpp \
    ../../../../src/calligra-v3.2.1/libs/widgetutils/KoProgressBar.cpp \
    ../../../../src/calligra-v3.2.1/libs/widgetutils/KoProgressUpdater.cpp \
    ../../../../src/calligra-v3.2.1/libs/widgetutils/KoUpdater.cpp \
    ../../../../src/calligra-v3.2.1/libs/widgetutils/KoUpdaterPrivate_p.cpp \
    ../../../../src/calligra-v3.2.1/libs/widgetutils/KoProperties.cpp \
    ../../../../src/calligra-v3.2.1/libs/widgetutils/KoFileDialog.cpp \
    ../../../../src/calligra-v3.2.1/libs/widgetutils/KoKineticScroller.cpp
