# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/libs/pageapp/tools/backgroundTool/kopabackgroundtool_autogen/mocs_compilation.cpp \
    ../../../../../../libs/pageapp/tools/backgroundTool/Plugin.cpp \
    ../../../../../../libs/pageapp/tools/backgroundTool/KoPABackgroundToolFactory.cpp \
    ../../../../../../libs/pageapp/tools/backgroundTool/KoPAMasterPageDocker.cpp
