# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../calligra/plugins/vectorshape/calligra_shape_vector_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/plugins/vectorshape/VectorDebug.cpp \
    ../../../../src/calligra-v3.2.1/plugins/vectorshape/VectorShapePlugin.cpp \
    ../../../../src/calligra-v3.2.1/plugins/vectorshape/VectorShape.cpp \
    ../../../../src/calligra-v3.2.1/plugins/vectorshape/VectorShapeConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/vectorshape/VectorShapeFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/vectorshape/VectorTool.cpp \
    ../../../../src/calligra-v3.2.1/plugins/vectorshape/VectorToolFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/vectorshape/ChangeVectorDataCommand.cpp
