# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../calligra/libs/vectorimage/kovectorimage_autogen/mocs_compilation.cpp \
    ../../../../libs/vectorimage/libemf/EmfRecords.cpp \
    ../../../../libs/vectorimage/libemf/EmfObjects.cpp \
    ../../../../libs/vectorimage/libemf/EmfHeader.cpp \
    ../../../../libs/vectorimage/libemf/BitmapHeader.cpp \
    ../../../../libs/vectorimage/libemf/Bitmap.cpp \
    ../../../../libs/vectorimage/libemf/EmfParser.cpp \
    ../../../../libs/vectorimage/libemf/EmfOutput.cpp \
    ../../../../libs/vectorimage/libemf/EmfOutputPainterStrategy.cpp \
    ../../../../libs/vectorimage/libsvm/SvmStructs.cpp \
    ../../../../libs/vectorimage/libsvm/SvmGraphicsContext.cpp \
    ../../../../libs/vectorimage/libsvm/SvmParser.cpp \
    ../../../../libs/vectorimage/libsvm/SvmPainterBackend.cpp \
    ../../../../libs/vectorimage/libwmf/WmfStack.cpp \
    ../../../../libs/vectorimage/libwmf/WmfDeviceContext.cpp \
    ../../../../libs/vectorimage/libwmf/WmfParser.cpp \
    ../../../../libs/vectorimage/libwmf/WmfAbstractBackend.cpp \
    ../../../../libs/vectorimage/libwmf/WmfPainterBackend.cpp \
    ../../../../libs/vectorimage/libwmf/WmfWriter.cpp \
    ../../../../libs/vectorimage/VectorImageDebug.cpp
