# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../calligra/filters/libodfreader/koodfreader_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdfReaderDebug.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdfReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdfReaderContext.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdfReaderBackend.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdfParser.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdtReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdtReaderBackend.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdsReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdsReaderBackend.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdfTextReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdfTextReaderBackend.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdfDrawReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdfDrawReaderBackend.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdfChartReader.cpp \
    ../../../../src/calligra-v3.2.1/filters/libodfreader/OdfChartReaderBackend.cpp
