# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../calligra/karbon/ui/karbonui_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/KarbonUiDebug.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/KarbonFactory.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/KarbonDocument.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/KarbonPart.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/KarbonView.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/ProxyView.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/KarbonDocumentMergeCommand.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/dialogs/KarbonConfigureDialog.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/widgets/KarbonSmallStylePreview.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/widgets/KarbonPaletteBarWidget.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/widgets/KarbonPaletteWidget.cpp \
    ../../../../src/calligra-v3.2.1/karbon/ui/widgets/KarbonConfigInterfacePage.cpp
