# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/filters/words/msword-odf/calligra_filter_doc2odt_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/msword-odf/MsDocDebug.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/msword-odf/mswordodfimport.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/msword-odf/document.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/msword-odf/conversion.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/msword-odf/texthandler.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/msword-odf/paragraph.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/msword-odf/tablehandler.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/msword-odf/graphicshandler.cpp \
    ../../../../../src/calligra-v3.2.1/filters/words/msword-odf/drawclient.cpp
