# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../calligra/plugins/formulashape/ui_FormulaToolWidget.h
SOURCES += ../../../calligra/plugins/formulashape/calligra_shape_formula_autogen/mocs_compilation.cpp \
    ../../../../plugins/formulashape/KoFormulaShapePlugin.cpp \
    ../../../../plugins/formulashape/KoFormulaShape.cpp \
    ../../../../plugins/formulashape/FormulaCommandUpdate.cpp \
    ../../../../plugins/formulashape/KoFormulaShapeFactory.cpp \
    ../../../../plugins/formulashape/KoFormulaTool.cpp \
    ../../../../plugins/formulashape/FormulaCommand.cpp \
    ../../../../plugins/formulashape/KoFormulaToolFactory.cpp \
    ../../../../plugins/formulashape/FormulaToolWidget.cpp \
    ../../../../plugins/formulashape/FormulaDocument.cpp \
    ../../../../plugins/formulashape/FormulaPart.cpp
FORMS += ../../../../plugins/formulashape/FormulaToolWidget.ui
