# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../calligra/plugins/formulashape/koformula_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/FormulaDebug.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/AttributeManager.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/FormulaRenderer.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/FormulaData.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/FormulaCursor.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/FormulaEditor.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/FormulaCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/ElementFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/Dictionary.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/BasicElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/FixedElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/RowElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/FormulaElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/TextElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/FractionElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/SpaceElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/GlyphElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/IdentifierElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/OperatorElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/MultiscriptElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/SubSupElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/UnderOverElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/FencedElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/TableElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/TableRowElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/TableDataElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/RootElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/EncloseElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/ActionElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/PaddedElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/ErrorElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/StyleElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/TokenElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/NumberElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/StringElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/PhantomElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/SquareRootElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/AnnotationElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/formulashape/elements/UnknownElement.cpp
