# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../calligra/plugins/videoshape/ui_VideoToolWidget.h
SOURCES += ../../../calligra/plugins/videoshape/calligra_shape_video_autogen/mocs_compilation.cpp \
    ../../../../plugins/videoshape/VideoDebug.cpp \
    ../../../../plugins/videoshape/VideoData.cpp \
    ../../../../plugins/videoshape/VideoCollection.cpp \
    ../../../../plugins/videoshape/VideoShape.cpp \
    ../../../../plugins/videoshape/VideoShapeFactory.cpp \
    ../../../../plugins/videoshape/VideoEventAction.cpp \
    ../../../../plugins/videoshape/Plugin.cpp \
    ../../../../plugins/videoshape/VideoShapeConfigWidget.cpp \
    ../../../../plugins/videoshape/FullScreenPlayer.cpp \
    ../../../../plugins/videoshape/VideoTool.cpp \
    ../../../../plugins/videoshape/VideoToolFactory.cpp \
    ../../../../plugins/videoshape/ChangeVideoCommand.cpp \
    ../../../../plugins/videoshape/SelectVideoWidget.cpp
FORMS += ../../../../plugins/videoshape/forms/VideoToolWidget.ui
