# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../calligra/plugins/variables/ui_FixedDateFormat.h
SOURCES += ../../../calligra/plugins/variables/calligra_textinlineobject_variables_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/VariablesDebug.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/VariablesPlugin.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/UserVariable.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/UserVariableFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/UserVariableOptionsWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/DateVariable.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/DateVariableFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/FixedDateFormat.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/PageVariable.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/PageVariableFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/InfoVariable.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/InfoVariableFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/ChapterVariable.cpp \
    ../../../../src/calligra-v3.2.1/plugins/variables/ChapterVariableFactory.cpp
FORMS += ../../../../src/calligra-v3.2.1/plugins/variables/FixedDateFormat.ui
