# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../calligra/libs/textlayout/kotextlayout_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextLayoutCellHelper.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextLayoutArea.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextLayoutArea_paint.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextLayoutEndNotesArea.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextLayoutTableArea.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextLayoutNoteArea.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextLayoutRootArea.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextLayoutRootAreaProvider.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextDocumentLayout.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/ListItemsHelper.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextShapeContainerModel.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/RunAroundHelper.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextLayoutObstruction.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/FrameIterator.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/TableIterator.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoPointedAt.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoTextShapeData.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/FloatingAnchorStrategy.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/InlineAnchorStrategy.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/AnchorStrategy.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/ToCGenerator.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/DummyDocumentLayout.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/IndexGeneratorManager.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/KoStyleThumbnailer.cpp \
    ../../../../src/calligra-v3.2.1/libs/textlayout/TextLayoutDebug.cpp
