# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/filters/karbon/xfig/calligra_filter_xfig2odg_autogen/mocs_compilation.cpp \
    ../../../../../src/calligra-v3.2.1/filters/karbon/xfig/XFigDocument.cpp \
    ../../../../../src/calligra-v3.2.1/filters/karbon/xfig/XFigStreamLineReader.cpp \
    ../../../../../src/calligra-v3.2.1/filters/karbon/xfig/XFigParser.cpp \
    ../../../../../src/calligra-v3.2.1/filters/karbon/xfig/XFigOdgWriter.cpp \
    ../../../../../src/calligra-v3.2.1/filters/karbon/xfig/XFigImportFilter.cpp
