# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../calligra/filters/karbon/xfig/calligra_filter_xfig2odg_autogen/mocs_compilation.cpp \
    ../../../../../filters/karbon/xfig/XFigDocument.cpp \
    ../../../../../filters/karbon/xfig/XFigStreamLineReader.cpp \
    ../../../../../filters/karbon/xfig/XFigParser.cpp \
    ../../../../../filters/karbon/xfig/XFigOdgWriter.cpp \
    ../../../../../filters/karbon/xfig/XFigImportFilter.cpp
