# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../calligra/stage/part/ui_KPrConfigureSlideShow.h \
    ../../../calligra/stage/part/ui_KPrConfigurePresenterView.h \
    ../../../calligra/stage/part/ui_KPrPresentationTool.h \
    ../../../calligra/stage/part/ui_KPrHtmlExport.h
SOURCES += ../../../calligra/stage/part/calligrastageprivate_autogen/mocs_compilation.cpp \
    ../../../../stage/part/StageDebug.cpp \
    ../../../../stage/part/KPrFactory.cpp \
    ../../../../stage/part/KPrDocument.cpp \
    ../../../../stage/part/KPrDeclarations.cpp \
    ../../../../stage/part/KPrPart.cpp \
    ../../../../stage/part/KPrView.cpp \
    ../../../../stage/part/KPrViewModePresentation.cpp \
    ../../../../stage/part/KPrViewModeNotes.cpp \
    ../../../../stage/part/KPrViewModeSlidesSorter.cpp \
    ../../../../stage/part/KPrViewModePreviewPageEffect.cpp \
    ../../../../stage/part/KPrViewModePreviewShapeAnimations.cpp \
    ../../../../stage/part/KPrPresentationTool.cpp \
    ../../../../stage/part/KPrAnimationDirector.cpp \
    ../../../../stage/part/KPrShapeAnimations.cpp \
    ../../../../stage/part/KPrShapeManagerAnimationStrategy.cpp \
    ../../../../stage/part/KPrShapeManagerDisplayMasterStrategy.cpp \
    ../../../../stage/part/KPrPageData.cpp \
    ../../../../stage/part/KPrPage.cpp \
    ../../../../stage/part/KPrMasterPage.cpp \
    ../../../../stage/part/KPrNotes.cpp \
    ../../../../stage/part/KPrSoundData.cpp \
    ../../../../stage/part/KPrSoundCollection.cpp \
    ../../../../stage/part/KPrEventActionData.cpp \
    ../../../../stage/part/KPrEventActionWidget.cpp \
    ../../../../stage/part/KPrPageApplicationData.cpp \
    ../../../../stage/part/KPrShapeApplicationData.cpp \
    ../../../../stage/part/KPrCustomSlideShows.cpp \
    ../../../../stage/part/KPrPresenterViewBaseInterface.cpp \
    ../../../../stage/part/KPrPresenterViewInterface.cpp \
    ../../../../stage/part/KPrPresenterViewSlidesInterface.cpp \
    ../../../../stage/part/KPrPresenterViewToolWidget.cpp \
    ../../../../stage/part/KPrPresenterViewWidget.cpp \
    ../../../../stage/part/KPrEndOfSlideShowPage.cpp \
    ../../../../stage/part/KPrPlaceholderShape.cpp \
    ../../../../stage/part/KPrPlaceholderShapeFactory.cpp \
    ../../../../stage/part/KPrPlaceholderStrategy.cpp \
    ../../../../stage/part/KPrPlaceholderPictureStrategy.cpp \
    ../../../../stage/part/KPrPlaceholderTextStrategy.cpp \
    ../../../../stage/part/KPrPresentationHighlightWidget.cpp \
    ../../../../stage/part/KPrPresentationDrawWidget.cpp \
    ../../../../stage/part/KPrPresentationBlackWidget.cpp \
    ../../../../stage/part/KPrPresentationStrategy.cpp \
    ../../../../stage/part/KPrPresentationHighlightStrategy.cpp \
    ../../../../stage/part/KPrPresentationBlackStrategy.cpp \
    ../../../../stage/part/KPrPresentationStrategyBase.cpp \
    ../../../../stage/part/KPrPresentationToolEventForwarder.cpp \
    ../../../../stage/part/KPrPresentationDrawStrategy.cpp \
    ../../../../stage/part/KPrPageSelectStrategyBase.cpp \
    ../../../../stage/part/KPrPageSelectStrategyFixed.cpp \
    ../../../../stage/part/KPrPageSelectStrategyActive.cpp \
    ../../../../stage/part/KPrDurationParser.cpp \
    ../../../../stage/part/KPrHtmlExport.cpp \
    ../../../../stage/part/KPrHtmlExportUiDelegate.cpp \
    ../../../../stage/part/KPrPicturesImport.cpp \
    ../../../../stage/part/KPrPdfPrintJob.cpp \
    ../../../../stage/part/KPrSlidesSorterDocumentModel.cpp \
    ../../../../stage/part/KPrSlidesManagerView.cpp \
    ../../../../stage/part/KPrCustomSlideShowsModel.cpp \
    ../../../../stage/part/KPrSlidesSorterItemDelegate.cpp \
    ../../../../stage/part/KPrPageLayoutWidget.cpp \
    ../../../../stage/part/KPrPageTransition.cpp \
    ../../../../stage/part/commands/KPrAnimationCreateCommand.cpp \
    ../../../../stage/part/commands/KPrAnimationRemoveCommand.cpp \
    ../../../../stage/part/commands/KPrPageEffectSetCommand.cpp \
    ../../../../stage/part/commands/KPrPageLayoutCommand.cpp \
    ../../../../stage/part/commands/KPrEditCustomSlideShowsCommand.cpp \
    ../../../../stage/part/commands/KPrAddCustomSlideShowCommand.cpp \
    ../../../../stage/part/commands/KPrDelCustomSlideShowCommand.cpp \
    ../../../../stage/part/commands/KPrRenameCustomSlideShowCommand.cpp \
    ../../../../stage/part/commands/KPrDeleteSlidesCommand.cpp \
    ../../../../stage/part/commands/KPrEditAnimationTimeLineCommand.cpp \
    ../../../../stage/part/commands/KPrAnimationEditNodeTypeCommand.cpp \
    ../../../../stage/part/commands/KPrReorderAnimationCommand.cpp \
    ../../../../stage/part/commands/KPrReplaceAnimationCommand.cpp \
    ../../../../stage/part/commands/KPrPageTransitionSetCommand.cpp \
    ../../../../stage/part/dockers/KPrPreviewWidget.cpp \
    ../../../../stage/part/pageeffects/KPrPageEffectRunner.cpp \
    ../../../../stage/part/pageeffects/KPrPageEffect.cpp \
    ../../../../stage/part/pageeffects/KPrPageEffectStrategy.cpp \
    ../../../../stage/part/pageeffects/KPrPageEffectFactory.cpp \
    ../../../../stage/part/pageeffects/KPrPageEffectRegistry.cpp \
    ../../../../stage/part/animations/KPrAnimationBase.cpp \
    ../../../../stage/part/animations/KPrAnimSet.cpp \
    ../../../../stage/part/animations/KPrAnimate.cpp \
    ../../../../stage/part/animations/KPrAnimateColor.cpp \
    ../../../../stage/part/animations/KPrAnimateMotion.cpp \
    ../../../../stage/part/animations/KPrAnimateTransform.cpp \
    ../../../../stage/part/animations/KPrAnimTransitionFilter.cpp \
    ../../../../stage/part/animations/KPrAnimationFactory.cpp \
    ../../../../stage/part/animations/KPrAnimationCache.cpp \
    ../../../../stage/part/animations/KPrTextBlockPaintStrategy.cpp \
    ../../../../stage/part/animations/KPrShapeAnimation.cpp \
    ../../../../stage/part/animations/KPrAnimationStep.cpp \
    ../../../../stage/part/animations/KPrAnimationSubStep.cpp \
    ../../../../stage/part/animations/KPrAnimationLoader.cpp \
    ../../../../stage/part/animations/KPrAnimationData.cpp \
    ../../../../stage/part/animations/strategy/KPrAnimationValue.cpp \
    ../../../../stage/part/animations/strategy/KPrFormulaParser.cpp \
    ../../../../stage/part/animations/strategy/KPrAnimationAttribute.cpp \
    ../../../../stage/part/animations/strategy/KPrSmilValues.cpp \
    ../../../../stage/part/animations/strategy/KPrAttributeX.cpp \
    ../../../../stage/part/animations/strategy/KPrAttributeY.cpp \
    ../../../../stage/part/animations/strategy/KPrAttributeWidth.cpp \
    ../../../../stage/part/animations/strategy/KPrAttributeHeight.cpp \
    ../../../../stage/part/animations/strategy/KPrAttributeRotate.cpp \
    ../../../../stage/part/pagelayout/KPrPlaceholder.cpp \
    ../../../../stage/part/pagelayout/KPrPageLayout.cpp \
    ../../../../stage/part/pagelayout/KPrPageLayouts.cpp \
    ../../../../stage/part/pagelayout/KPrPageLayoutSharedSavingData.cpp \
    ../../../../stage/part/pagelayout/KPrPlaceholders.cpp \
    ../../../../stage/part/ui/KPrConfigureSlideShowDialog.cpp \
    ../../../../stage/part/ui/KPrConfigurePresenterViewDialog.cpp \
    ../../../../stage/part/ui/KPrPresentationToolWidget.cpp \
    ../../../../stage/part/ui/KPrHtmlExportDialog.cpp \
    ../../../../stage/part/tools/KPrPlaceholderTool.cpp \
    ../../../../stage/part/tools/KPrPlaceholderToolFactory.cpp \
    ../../../../stage/part/KPrViewAdaptor.cpp \
    ../../../../stage/part/KPrPresentationToolAdaptor.cpp
FORMS += ../../../../stage/part/ui/KPrConfigureSlideShow.ui \
    ../../../../stage/part/ui/KPrConfigurePresenterView.ui \
    ../../../../stage/part/ui/KPrPresentationTool.ui \
    ../../../../stage/part/ui/KPrHtmlExport.ui
