# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../calligra/plugins/shapefiltereffects/calligra_filtereffects_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/FilterEffectsPlugin.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/BlurEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/BlurEffectFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/BlurEffectConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/OffsetEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/OffsetEffectFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/OffsetEffectConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/MergeEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/MergeEffectFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/MergeEffectConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ColorMatrixEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ColorMatrixEffectFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ColorMatrixEffectConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/FloodEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/FloodEffectFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/FloodEffectConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/CompositeEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/CompositeEffectFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/CompositeEffectConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/BlendEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/BlendEffectFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/BlendEffectConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ComponentTransferEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ComponentTransferEffectFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ComponentTransferEffectConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ImageEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ImageEffectFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ImageEffectConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/MorphologyEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/MorphologyEffectFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/MorphologyEffectConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ConvolveMatrixEffect.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ConvolveMatrixEffectFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/ConvolveMatrixEffectConfigWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/shapefiltereffects/MatrixDataModel.cpp
