# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../calligra/plugins/musicshape/ui_PartsWidget.h \
    ../../../calligra/plugins/musicshape/ui_PartDetailsDialog.h \
    ../../../calligra/plugins/musicshape/ui_SimpleEntryWidget.h \
    ../../../calligra/plugins/musicshape/ui_KeySignatureDialog.h
SOURCES += ../../../calligra/plugins/musicshape/calligra_shape_music_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/MusicDebug.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/MusicShape.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/MusicShapeFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/MusicTool.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/MusicToolFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/SimpleEntryTool.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/SimpleEntryToolFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/MusicStyle.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/Engraver.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/Renderer.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/MusicCursor.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/dialogs/PartsWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/dialogs/PartDetailsDialog.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/dialogs/SimpleEntryWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/dialogs/PartsListModel.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/dialogs/KeySignatureDialog.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/dialogs/StaffElementPreviewWidget.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/AbstractMusicAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/AbstractNoteMusicAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/NoteEntryAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/AccidentalAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/EraserAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/DotsAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/SetClefAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/TimeSignatureAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/KeySignatureAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/RemoveBarAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/TiedNoteAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/actions/SelectionAction.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/AddPartCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/RemovePartCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/ChangePartDetailsCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/CreateChordCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/AddNoteCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/SetAccidentalsCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/AddBarsCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/RemoveNoteCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/RemoveChordCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/AddDotCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/SetClefCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/RemoveStaffElementCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/SetTimeSignatureCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/SetKeySignatureCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/RemoveBarCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/MakeRestCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/commands/ToggleTiedNoteCommand.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/Global.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/Sheet.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/Part.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/PartGroup.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/Staff.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/Voice.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/Bar.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/VoiceBar.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/VoiceElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/StaffElement.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/Chord.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/Note.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/Clef.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/KeySignature.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/TimeSignature.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/StaffSystem.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/MusicXmlWriter.cpp \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/core/MusicXmlReader.cpp
FORMS += ../../../../src/calligra-v3.2.1/plugins/musicshape/dialogs/PartsWidget.ui \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/dialogs/PartDetailsDialog.ui \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/dialogs/SimpleEntryWidget.ui \
    ../../../../src/calligra-v3.2.1/plugins/musicshape/dialogs/KeySignatureDialog.ui
