# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../../../calligra/filters/words/rtf/import/calligra_filter_rtf2odt_autogen/mocs_compilation.cpp \
    ../../../../../../filters/words/rtf/import/rtfimport.cpp
