# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += ../../../calligra/plugins/dockers/calligra_docker_defaults_autogen/mocs_compilation.cpp \
    ../../../../src/calligra-v3.2.1/plugins/dockers/snapguidedocker/SnapGuideDocker.cpp \
    ../../../../src/calligra-v3.2.1/plugins/dockers/snapguidedocker/SnapGuideDockerFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/dockers/shapeproperties/ShapePropertiesDocker.cpp \
    ../../../../src/calligra-v3.2.1/plugins/dockers/shapeproperties/ShapePropertiesDockerFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/dockers/shapecollection/CollectionShapeFactory.cpp \
    ../../../../src/calligra-v3.2.1/plugins/dockers/shapecollection/ShapeCollectionDocker.cpp \
    ../../../../src/calligra-v3.2.1/plugins/dockers/shapecollection/CollectionItemModel.cpp \
    ../../../../src/calligra-v3.2.1/plugins/dockers/shapecollection/OdfCollectionLoader.cpp \
    ../../../../src/calligra-v3.2.1/plugins/dockers/Plugin.cpp
